---
- name: Install the application
  hosts: all

  vars:
    project_path: /app
    bower_path: bower
    extra_path: ./vendor/bin

  roles:
    - { role: kosssi.composer, become: true }

  tasks:
    - name: "Add {{ extra_path }} to path"
      lineinfile:
        dest: ~/.profile
        state: present
        backrefs: yes
        regexp: '^PATH=(["]*)((?!.*?{{ extra_path }}).*?)(["]*)$'
        line: 'PATH=\1\2:{{ extra_path }}\3'

    - name: Add composer github token
      command: >
        {{ composer_path }} config --global github-oauth.github.com {{ composer_github_oauth }}
      when: composer_github_oauth != "" and composer_github_oauth != false

    - name: Install asset dependencies
      command: >
        {{ bower_path }} install --production --silent
      args:
        chdir: "{{ project_path }}"
        creates: "{{ project_path }}/bower_components"

    - name: Install composer dependencies
      command: >
        {{ composer_path }} install --no-interaction
      args:
        chdir: "{{ project_path }}"
